display:
  inverted: false
  maximalist: false
  feedurl: https://news.hodlhodl.com/news.rss
  vcom: -2.61
ticker:
  currency: bitcoin,ethereum,dash
  exchange: default
  fiatcurrency: usd,eur,gbp
  updatefrequency: 180
  sparklinedays: 28
function: 
  mode: crypto
