display:
  inverted: false
  orientation: 90
ticker:
  currency: ethereum,litecoin,bitcoin-cash,stellar,monero,uniswap,bitcoin
  exchange: default
  fiatcurrency: eur,jpy,chf,gbp,usd
  updatefrequency: 600
  sparklinedays: 3 
