display:
  inverted: false
  maximalist: false
  feedurl: https://bitcoinmagazine.com/.rss/full/
  vcom: -2.61
  coinnames: false 
  xshift: 0
  yshift: 0
ticker:
  currency: bitcoin, ethereum, cardano, binancecoin
  exchange: default
  fiatcurrency: usd
  updatefrequency: 60
  sparklinedays: 14
  coinsperpage: 4
function: 
  mode: crypto,redditquotes, wordaday, newyorkercartoon, guardianheadlines, textfilequotes
  weight: 20, 1, 1, 1, 0, 0
