display:
  inverted: false
  maximalist: true
  feedurl: https://bitcoinmagazine.com/feed 
  vcom: -2.61
  coinnames: false 
ticker:
  currency: bitcoin
  exchange: default
  fiatcurrency: usd,eur,gbp
  updatefrequency: 180
  sparklinedays: 28
  coinsperpage: 3
function: 
  mode: crypto,redditquotes, wordaday, newyorkercartoon, guardianheadlines, textfilequotes
  weight: 50, 0, 0, 0 , 0, 0 
